### ISSUE TITLE
Could you please supply your project Logo for us to display on our Crab website?

### ISSUE THREAD

**Issue by 1022ranji** [Entity54/DarwiniaHackathon#1]
<img width="844" alt="image" src="https://user-images.githubusercontent.com/80877629/167595039-40f4c6a6-6684-4d96-aae1-cd09488fa9e8.png">

**Comment by Entity54** [comment]
Hi Ranji,

 
Please find attached.

If you need a certain size, let us know and we will resend.

Thanks,


Entity54.

 
From: RANJI ***@***.***>
Reply to: Entity54/DarwiniaHackathon ***@***.***>
Date: Tuesday, 10 May 2022 at 11:20
To: Entity54/DarwiniaHackathon ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Entity54/DarwiniaHackathon] Could you please supply your project Logo for us to display on our Crab website? (Issue #1)

 
 <https://user-images.githubusercontent.com/80877629/167595039-40f4c6a6-6684-4d96-aae1-cd09488fa9e8.png>

**Comment by Entity54** [comment]
![Entity 54_Logo Long 72](https://user-images.githubusercontent.com/42042104/167641047-e459b390-b5de-48ee-9883-374c4fa08e0d.png)

**Comment by 1022ranji** [comment]
Thanks! This Logo size is fine!
